#!/usr/bin/env python
import rospy
from sensor_msgs.msg import LaserScan
from ackermann_msgs.msg import AckermannDriveStamped

d_desired = .5
steering_angle = 0

def callBack(msg):
        ranges = msg.ranges
	distance = min(ranges)
	if d_desired > distance:
		steering_angle = .5
	else:
		steering_angle = -.5
	drive()

def drive():
        msg = AckermannDriveStamped();
    #msg.header.stamp = rospy.Time.now();
    #msg.header.frame_id = "base_link";
        msg.drive.speed = 3
        msg.drive.acceleration = 0
        msg.drive.jerk = 1
        msg.drive.steering_angle = steering_angle
        msg.drive.steering_angle_velocity = 1
        pub.publish(msg)

scanResult = rospy.Subscriber("racecar/laser/scan",LaserScan,callBack)
pub = rospy.Publisher('/racecar/ackermann_cmd_mux/input/safety', AckermannDriveStamped,queue_size=10)
rospy.init_node('one_point')
rospy.spin()
